baseURL = "https://alessiovalentini.com"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Alessio Valentini Homepage"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Resume"
url = "#about"
weight = 2
#[[menu.main]]
#name = "Service"
#url = "#service"
#weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Background"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
#[[menu.main]]
#name = "Blog"
#url = "#blog"
#weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

## Sitemap Menu
#[[menu.sitemap]]
#name = "About me"
#url = "about"
#weight = 1
#[[menu.sitemap]]
#name = "Frequently Ask Question"
#url = "#"
#weight = 2
#[[menu.sitemap]]
#name = "Privacy & Policy"
#url = "#"
#weight = 3
#[[menu.sitemap]]
#name = "Latest Article"
#url = "#"
#weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logoAV.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logoAV.png"

[params.address]
address = "Palo alto, California"
email = "alevale@stanford.edu"

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/alessio-valentini-a6157479/"
weight = 1
